//----------------------------------------------------------------------------
//  src/engine/cdp/processes/cdp_filter.cpp
//
//  Ported from the CDP FILTER family (vendor/cdp8/dev/filter), which is
//      Copyright (c) 1983-2013 Trevor Wishart and Composers Desktop Project Ltd
//      LGPL 2.1 -- see vendor/cdp8/LICENSE
//
//  Specifically:
//      ap_filter.c   get_coeffs1 / get_coeffs2 -- the resonator design
//      filters0.c    filtering() / io_filtering() -- the recursion, and the
//                    FLT_DBLFILT second pass
//
//  CDP's filter is a PARALLEL BANK of 2-pole resonators summed together.  Each
//  resonator is designed straight from its centre frequency and a shared Q:
//
//      ww   = 2*pi*frq/sr        r = exp(-ww / (2*Q))
//      a    = 2*r*cos(ww)        b = -r*r
//      g    = 1 / ((1 + b) * sin(ww))        amplitude is divided by g
//
//  and run as
//
//      xx = in + a*y + b*z ;  z = y ;  y = xx
//      (double mode repeats it through a second state pair)
//      sum += xx * ampl
//
//  What was welded on and has been dropped: argv parsing, the `dataptr dz`
//  parameter blocks, breakpoint-file sweeping of frequency/Q, the read/write
//  soundfile ping-pong, and the overflow-reporting/normalising passes that only
//  existed because CDP wrote 16-bit files.  The DSP is untouched.
//
//  THIS IS THE ZERO-LATENCY FAMILY.  A recursive filter needs no lookahead at
//  all, so these are the only ports so far that provide makeStream() -- the
//  generated rack module then runs them sample-by-sample with no added delay,
//  rather than buffering a chunk.
//----------------------------------------------------------------------------
#include "../cdp_process.h"

#include <algorithm>
#include <cmath>

namespace PatchKnob { namespace cdp {

std::vector<Process>& mutable_registry();

namespace {

constexpr double kPi = 3.14159265358979323846;
constexpr int    kMaxBank = 16;

//! One resonator's design, exactly as CDP's get_coeffs1/get_coeffs2 derive it.
struct Reso {
    double a = 0.0, b = 0.0, ampl = 0.0;
    void design(double frq, double q, double amp, double sr, bool dbl) {
        if (sr <= 0.0) sr = 48000.0;
        // Keep the centre inside the band: a resonator placed at or beyond
        // Nyquist has sin(ww) -> 0 and the gain normalisation below explodes.
        const double top = sr * 0.49;
        frq = std::max(1.0, std::min(top, frq));
        q   = std::max(0.5, q);
        const double ww   = 2.0 * kPi * frq / sr;
        const double cosw = std::cos(ww), sinw = std::sin(ww);
        const double r    = std::exp(-ww / (2.0 * q));
        a = 2.0 * r * cosw;
        b = -(r * r);
        const double denom = (1.0 + b) * sinw;
        const double g = std::fabs(denom) > 1e-12 ? 1.0 / denom : 1.0;
        ampl = (std::fabs(g) > 1e-12) ? amp / g : 0.0;
        if (dbl && std::fabs(g) > 1e-12) ampl /= g;
    }
};

//! Per-channel state for one resonator (y/z, plus d/z1 for the double pass).
struct ResoState { double y = 0, z = 0, d = 0, z1 = 0; };

//! The bank, shared by the offline and streaming paths so both run identical
//! arithmetic -- an offline render and its live preview must not diverge.
struct Bank {
    Reso  reso[kMaxBank];
    int   count = 1;
    bool  dbl = false;
    double gain = 1.0;

    void build(double baseFrq, double q, double gainIn, int n, bool dblIn,
               double spacing, double sr) {
        count = std::max(1, std::min(kMaxBank, n));
        dbl = dblIn;
        gain = gainIn;
        for (int i = 0; i < count; ++i) {
            // CDP drives the bank from a frequency LIST; here the list is
            // generated by stacking `spacing` semitones per resonator, which is
            // what the harmonic/subharmonic presets in the CDP docs describe.
            const double f = baseFrq * std::pow(2.0, (spacing * i) / 12.0);
            reso[i].design(f, q, 1.0 / (double)count, sr, dbl);
        }
    }

    inline float tick(float in, ResoState* st) const {
        double sum = 0.0;
        const double x = (double)in;
        for (int f = 0; f < count; ++f) {
            ResoState& s = st[f];
            double xx = x + reso[f].a * s.y + reso[f].b * s.z;
            s.z = s.y; s.y = xx;
            if (dbl) {
                xx += reso[f].a * s.d + reso[f].b * s.z1;
                s.z1 = s.d; s.d = xx;
            }
            sum += xx * reso[f].ampl;
        }
        sum *= gain;
        if (!std::isfinite(sum)) { sum = 0.0; }
        // CDP clipped to the 16-bit file range here; we keep float headroom but
        // still fence the recursion so a runaway cannot leave the module.
        return (float)std::max(-8.0, std::min(8.0, sum));
    }
};

Bank bank_from(const std::vector<double>& p, double sr) {
    auto at = [&](size_t i, double d) { return i < p.size() ? p[i] : d; };
    Bank b;
    b.build(at(0, 440.0), at(1, 20.0), at(4, 1.0),
            (int)std::lround(at(2, 1.0)), at(5, 0.0) >= 0.5, at(3, 12.0), sr);
    return b;
}

//! Live instance: no lookahead, no allocation in process().
struct FilterStream final : Stream {
    Bank bank;
    ResoState st[8][kMaxBank] = {};      // up to 8 channels, independent state

    void process(float* const* ch, int channels, int n) override {
        const int cn = std::min(channels, 8);
        for (int c = 0; c < cn; ++c)
            for (int i = 0; i < n; ++i)
                ch[c][i] = bank.tick(ch[c][i], st[c]);
    }
    void reset() override {
        for (int c = 0; c < 8; ++c)
            for (int f = 0; f < kMaxBank; ++f) st[c][f] = ResoState{};
    }
};

bool filter_run(const std::vector<Buffer>& in, const std::vector<double>& p,
                Buffer& out, std::string& err, const Progress& prog) {
    if (in.empty() || in[0].empty()) { err = "no input"; return false; }
    const double sr = in[0].sampleRate > 0 ? in[0].sampleRate : 48000;
    out = in[0];
    const Bank bank = bank_from(p, sr);
    for (int c = 0; c < out.channels(); ++c) {
        ResoState st[kMaxBank] = {};      // state per channel, reset per call
        std::vector<float>& x = out.ch[(size_t)c];
        for (size_t i = 0; i < x.size(); ++i) x[i] = bank.tick(x[i], st);
        if (prog && !prog((double)(c + 1) / (double)out.channels())) {
            err = "cancelled"; return false;
        }
    }
    return true;
}

} // namespace

void register_filter_processes() {
    Process p;
    p.slug  = "filter.bank";
    p.name  = "Filter Bank";
    p.group = "Filter";
    p.help  = "Parallel bank of 2-pole resonators, CDP's filter design.";
    p.streamable = true;
    // A recursive filter is causal and needs no lookahead whatsoever.
    p.latencyFrames = [](int, const std::vector<double>&) -> int64_t { return 0; };
    p.params = {
        { "Frequency", "Hz", 20.0, 18000.0, 440.0, false,
          "Centre of the lowest resonator." },
        { "Q", "", 0.5, 200.0, 20.0, false,
          "Resonance sharpness; higher rings longer." },
        { "Count", "", 1, kMaxBank, 1, true,
          "How many resonators are stacked." },
        { "Spacing", "semitones", -24.0, 24.0, 12.0, false,
          "Interval between successive resonators." },
        { "Gain", "", 0.0, 4.0, 1.0, false, "Output gain." },
        { "Double", "", 0, 1, 0, true,
          "Run each resonator twice for a steeper response." },
    };
    p.makeStream = [](int sr, const std::vector<double>& pr) -> std::unique_ptr<Stream> {
        auto s = std::unique_ptr<FilterStream>(new FilterStream());
        s->bank = bank_from(pr, sr > 0 ? sr : 48000);
        s->reset();
        return s;
    };
    p.run = &filter_run;
    mutable_registry().push_back(p);
}

} } // namespace PatchKnob::cdp
