//----------------------------------------------------------------------------
//  src/engine/buzz/buzz_host.cpp -- see buzz_host.h.
//----------------------------------------------------------------------------
#include "buzz_host.h"
#include "mdk.h"           // CMDKMachineInterface (mdkimp.h references it)
#include "mdkimp.h"        // CMDKImplementation (MDK factory hack)
#include "OscTable.h"      // OscTable[6][4096]

#include <cstdio>
#include <cstring>

// Init functions of the compiled-in machines (global scope; each is generated by
// that machine's DLL_EXPORTS(<init>) under STATIC_BUILD).
void unwieldy_register();

namespace PatchKnob { namespace buzz {

// --- STATIC_BUILD registry --------------------------------------------------
static std::vector<MachineReg>& registry() { static std::vector<MachineReg> g; return g; }

const std::vector<MachineReg>& registered_machines() { return registry(); }

void register_builtin_machines() {
    static bool done = false;
    if (done) return;
    done = true;
    ::unwieldy_register();  // global (DLL_EXPORTS); referencing it pulls in unwieldy_tracker.o
}

CMachineInterface* create_machine(const std::string& name, CMachineInfo const** infoOut) {
    for (const MachineReg& r : registry())
        if (r.name == name && r.create) {
            if (infoOut) *infoOut = r.getInfo ? r.getInfo() : r.info;
            return r.create();
        }
    return nullptr;
}

}} // namespace PatchKnob::buzz

// RegisterMachine is what the SDK's DLL_EXPORTS(INIT_FUNC) macro calls under
// STATIC_BUILD.  It lives in the GLOBAL namespace (that is how the macro names it).
void RegisterMachine(CMachineInfo const* pmi,
                     PatchKnob::buzz::BuzzGetInfoFn gi,
                     PatchKnob::buzz::BuzzCreateFn cm) {
    using namespace PatchKnob::buzz;
    MachineReg r;
    r.info = pmi; r.getInfo = gi; r.create = cm;
    r.name = (pmi && pmi->Name) ? pmi->Name : "";
    registry().push_back(r);
}

namespace PatchKnob { namespace buzz {

// --- BuzzHost ---------------------------------------------------------------
BuzzHost::BuzzHost() {
    waves.resize(1);                 // slot 0 is a dead placeholder (waves are 1-based)
    aux_.assign(2 * MAX_BUFFER_LENGTH, 0.f);
    master.BeatsPerMin = 126; master.TicksPerBeat = 4;
    master.SamplesPerSec = 44100;
    master.SamplesPerTick = (int)((60.0 * master.SamplesPerSec) / (master.BeatsPerMin * master.TicksPerBeat));
    master.PosInTick = 0;
    master.TicksPerSec = (float)master.SamplesPerSec / (float)master.SamplesPerTick;
}
BuzzHost::~BuzzHost() {}

void BuzzHost::clearWave(int wave) {
    std::lock_guard<std::mutex> lk(mtx_);
    if (wave >= 1 && wave < (int)waves.size()) {
        for (WaveLevelData& level : waves[(size_t)wave].levels)
            if (!level.samples.empty())
                retiredSamples.push_back(std::move(level.samples));
        waves[(size_t)wave] = WaveSlot{};
    }
}

void BuzzHost::setEnvelope(int wave, int env, const HostEnvPoint* pts, int count) {
    if (wave < 1 || env < 0 || env > 4) return;
    std::lock_guard<std::mutex> lk(mtx_);
    if (wave >= (int)waves.size()) waves.resize((size_t)wave + 1);
    WaveSlot& s = waves[(size_t)wave];
    s.used = true;
    if (env >= (int)s.envelopes.size()) s.envelopes.resize((size_t)env + 1);
    s.envelopes[(size_t)env].assign(pts, pts + std::max(0, count));
}

void BuzzHost::setWaveLevel(int wave, int level, const short* interleaved, int numFrames,
                            bool stereo, int rootNote, int samplesPerSec,
                            int loopStart, int loopEnd, bool loop,
                            int loKey, int hiKey, const char* name) {
    if (wave < 1 || numFrames <= 0 || !interleaved) return;
    std::lock_guard<std::mutex> lk(mtx_);
    if (wave >= (int)waves.size()) waves.resize((size_t)wave + 1);
    WaveSlot& s = waves[(size_t)wave];
    s.used = true;
    if (name) s.name = name;
    s.info.Flags  = (loop ? WF_LOOP : 0) | (stereo ? WF_STEREO : 0);
    s.info.Volume = 1.0f;
    if (level < 0) level = 0;
    if (level >= (int)s.levels.size()) s.levels.resize((size_t)level + 1);
    WaveLevelData& L = s.levels[(size_t)level];
    const int chans = stereo ? 2 : 1;
    if (!L.samples.empty())
        retiredSamples.push_back(std::move(L.samples));
    L.samples.assign(interleaved, interleaved + (size_t)numFrames * chans);
    L.level.numSamples    = numFrames;
    L.level.pSamples      = L.samples.data();
    L.level.RootNote      = rootNote;
    L.level.SamplesPerSec = samplesPerSec;
    L.level.LoopStart     = loopStart;
    L.level.LoopEnd       = loopEnd > 0 ? loopEnd : numFrames;
    L.loKey = loKey; L.hiKey = hiKey;
}

// --- CMICallbacks: wavetable ------------------------------------------------
CWaveInfo const* BuzzHost::GetWave(int const i) {
    if (i >= 1 && i < (int)waves.size() && waves[(size_t)i].used) return &waves[(size_t)i].info;
    return &dummyInfo_;
}
CWaveLevel const* BuzzHost::GetWaveLevel(int const i, int const level) {
    if (i >= 1 && i < (int)waves.size() && waves[(size_t)i].used) {
        const WaveSlot& s = waves[(size_t)i];
        if (level >= 0 && level < (int)s.levels.size() && s.levels[(size_t)level].level.numSamples > 0)
            return &s.levels[(size_t)level].level;
    }
    return nullptr;
}
CWaveLevel const* BuzzHost::GetNearestWaveLevel(int const i, int const note) {
    // MDK factory hack: the machine's CMDKMachineInterface::Init asks the host for
    // a fresh CMDKImplementation via GetNearestWaveLevel(-1,-1).
    if (i == -1 && note == -1) return (CWaveLevel const*)(void*)new CMDKImplementation;
    if (i < 1 || i >= (int)waves.size() || !waves[(size_t)i].used) return nullptr;
    const WaveSlot& s = waves[(size_t)i];
    // Among levels whose keyrange COVERS the note, pick the one whose root is
    // NEAREST the note; only if none cover it, fall back to the globally nearest
    // root.  (Returning the FIRST keyrange match broke multisampling: with two
    // samples both loaded full-range 0..127, every note resolved to level 0, so a
    // C#4 note played the C4 sample -- "the snare plays the kick".)
    const WaveLevelData* best = nullptr;        int bestDist = 1 << 30;
    const WaveLevelData* inRange = nullptr;     int inRangeDist = 1 << 30;
    for (const WaveLevelData& L : s.levels) {
        if (L.level.numSamples <= 0) continue;
        int d = note - L.level.RootNote; if (d < 0) d = -d;
        if (note >= L.loKey && note <= L.hiKey) {
            if (d < inRangeDist) { inRangeDist = d; inRange = &L; }
        }
        if (d < bestDist) { bestDist = d; best = &L; }
    }
    if (inRange) return &inRange->level;
    return best ? &best->level : nullptr;
}
int  BuzzHost::GetFreeWave() {
    for (int i = 1; i < (int)waves.size(); ++i) if (!waves[(size_t)i].used) return i;
    return (int)waves.size();
}
bool BuzzHost::AllocateWave(int const, int const, char const*) { return false; }
char const* BuzzHost::GetWaveName(int const i) {
    if (i >= 1 && i < (int)waves.size() && waves[(size_t)i].used) return waves[(size_t)i].name.c_str();
    return "";
}
void BuzzHost::SetInternalWaveName(CMachine*, int const, char const*) {}

// --- CMICallbacks: misc host services --------------------------------------
void  BuzzHost::MessageBox(char const* txt) { std::fprintf(stderr, "[buzz] %s\n", txt ? txt : ""); }
void  BuzzHost::Lock()   { mtx_.lock(); }
void  BuzzHost::Unlock() { mtx_.unlock(); }
int   BuzzHost::GetWritePos() { return 0; }
int   BuzzHost::GetPlayPos()  { return 0; }
float* BuzzHost::GetAuxBuffer() { return aux_.data(); }
void  BuzzHost::ClearAuxBuffer() { std::memset(aux_.data(), 0, aux_.size() * sizeof(float)); }
void  BuzzHost::ScheduleEvent(int const, dword const) {}
void  BuzzHost::MidiOut(int const, dword const) {}
short const* BuzzHost::GetOscillatorTable(int const waveform) {
    int w = waveform; if (w < 0) w = 0; if (w > 5) w = 5;
    return OscTable[w];
}
int   BuzzHost::GetEnvSize(int const wave, int const env) {
    if (wave >= 1 && wave < (int)waves.size() && env >= 0 && env < (int)waves[(size_t)wave].envelopes.size())
        return (int)waves[(size_t)wave].envelopes[(size_t)env].size();
    return 0;
}
bool  BuzzHost::GetEnvPoint(int const wave, int const env, int const i, word& x, word& y, int& flags) {
    if (wave < 1 || wave >= (int)waves.size()) return false;
    if (env < 0 || env >= (int)waves[(size_t)wave].envelopes.size()) return false;
    const std::vector<HostEnvPoint>& e = waves[(size_t)wave].envelopes[(size_t)env];
    if (i < 0 || i >= (int)e.size()) return false;
    x = e[(size_t)i].x; y = e[(size_t)i].y; flags = e[(size_t)i].flags;
    return true;
}
void  BuzzHost::SetNumberOfTracks(int const) {}
CPattern* BuzzHost::CreatePattern(char const*, int const) { return nullptr; }
CPattern* BuzzHost::GetPattern(int const) { return nullptr; }
char const* BuzzHost::GetPatternName(CPattern*) { return ""; }
void  BuzzHost::RenamePattern(char const*, char const*) {}
void  BuzzHost::DeletePattern(CPattern*) {}
int   BuzzHost::GetPatternData(CPattern*, int const, int const, int const, int const) { return 0; }
void  BuzzHost::SetPatternData(CPattern*, int const, int const, int const, int const, int const) {}
CSequence* BuzzHost::CreateSequence() { return nullptr; }
void  BuzzHost::DeleteSequence(CSequence*) {}
CPattern* BuzzHost::GetSequenceData(int const) { return nullptr; }
void  BuzzHost::SetSequenceData(int const, CPattern*) {}
void  BuzzHost::SetMachineInterfaceEx(CMachineInterfaceEx* pex) { ex_ = pex; }
void  BuzzHost::ControlChange__obsolete__(int, int, int, int) {}
int   BuzzHost::ADGetnumChannels(bool) { return 2; }
void  BuzzHost::ADWrite(int, float*, int) {}
void  BuzzHost::ADRead(int, float*, int) {}
CMachine* BuzzHost::GetThisMachine() { return (CMachine*)this; }   // opaque handle
void  BuzzHost::ControlChange(CMachine*, int, int, int, int) {}
CSequence* BuzzHost::GetPlayingSequence(CMachine*) { return nullptr; }
void* BuzzHost::GetPlayingRow(CSequence*, int, int) { return nullptr; }
int   BuzzHost::GetStateFlags() { return stateFlags; }
void  BuzzHost::SetnumOutputChannels(CMachine*, int n) { outChannels = n; }
void  BuzzHost::SetEventHandler(CMachine*, BEventType, EVENT_HANDLER_PTR, void*) {}
void  BuzzHost::GetMachineNames(CMachineDataOutput*) {}
CMachine* BuzzHost::GetMachine(char const*) { return nullptr; }
CMachineInfo const* BuzzHost::GetMachineInfo(CMachine*) { return nullptr; }
char const* BuzzHost::GetMachineName(CMachine*) { return ""; }
bool  BuzzHost::GetInput(int, float*, int, bool, float*) { return false; }

}} // namespace PatchKnob::buzz
